# Site settings
title: 'Sefer Design Co.'
company_name: 'Sefer Design Company LLC'
description: 'Chicago Web Design and Web Development'
descriptionLong: 'Chicago Web Design and Web Development. We build sites and tools for the modern web.'
baseurl: ''
distbase: '/dist'
production_url_base: 'https://seferdesign.com'

source: _src

# Build settings
permalink: pretty
include: [
  '.htaccess',
  '_src/_pages'
]
exclude: [
  'node_modules',
  'package.json',
  'package-lock.json',
  'gulpfile.js',
  'README.md',
  'SOURCE',
  'assets/'
]
languages: ['en']
