# Site settings
title: Sefer Design Co.
description: Chicago Web Design &amp; Web Products

# Build settings
markdown: kramdown
permalink: pretty

exclude: [
  'node_modules',
  'package.json',
  'bower_components',
  'bower.json',
  'Gruntfile.js'
]
