# Site settings
title: 'Sefer Design Co.'
company_name: 'Sefer Design Company LLC'
description: 'Chicago Web Design and Web Development'
baseurl: ''
distbase: '/dist'

# Build settings
permalink: pretty
exclude: [
  'node_modules',
  'package.json',
  'gulpfile.js',
  'README.md',
  'SOURCE'
]
languages: ['en']
