# Site settings
title: 'Sefer Design Co.'
company_name: 'Sefer Design Company LLC'
description: 'Chicago Web Design and Web Development'
baseurl: ''
distbase: '/dist'
production_url_base: 'https://seferdesign.com'

source: _src

# Build settings
permalink: pretty
exclude: [
  'node_modules',
  'package.json',
  'package-lock.json',
  'gulpfile.js',
  'README.md',
  'SOURCE',
  'assets/'
]
languages: ['en']
